In [12]:
import pandas as pd
from pandas import DataFrame

path = '../data/product_catalog.csv'
df = pd.read_csv(path)
df

,sku,product_name,category,subcategory,unit_cost,supplier,package_size
0,PT-12,pop-tarts strawberry,Breakfast Foods,NaN,1.93,Johnson & Johnson,4-pack
1,SKU#459812,Strawberry Pop-Tart,Breakfast,Pop-Tarts,2.26,Roku Inc,4pk
2,POPTART-STRAW,Pop-Tarts Strawberry,Breakfast,NaN,2.11,Sara Lee,6 pack
3,PT_STRAWBERRY,pop-tarts strawberry,breakfast,Pop-Tarts,NaN,Campbell's,4 pack
4,WTR-24,BOTTLED WATER 24PK,Emergency Supplies,Bottled,2.64,Sara Lee,1 pack
5,WATER24PK,Bottled Water 24-Pack,Emergency,Bottled,2.38,Sara Lee,24 pack
6,WTR_24PK,Water - 24 Pack,Emergency,NaN,2.08,Frito-Lay,1 pack
7,BATT-100,BATTERIES AA 4PK,Emergency Supplies,AA,NaN,3M Company,6 pack
8,BAT-AA4,AA Batteries 4-Pack,Emergency Supplies,AA,4.16,Kimberly-Clark,4pk
9,BATT_AA_4PK,AA Batteries 4-Pack,Emergency,AA,3.71,Anheuser-Busch,24 pack
10,FLASH-01,FLASHLIGHT LED,Emergency,Flashlight,NaN,Frito-Lay,6-pack
11,LED-FLASH,FLASHLIGHT LED,EMERGENCY,NaN,8.20,Frito-Lay,single
12,BEER-24,Light Beer (24-pack),Alcoholic Beverages,NaN,9.62,Hasbro,bundle
13,LTBEER24,Light Beer (24-pack),ALCOHOL,Light,7.61,Kellogg's,bundle
14,BG-MONO,Monopoly Board Game,ENTERTAINMENT,NaN,9.96,Kimberly-Clark,1pk
15,MONOPOLY-01,Monopoly Board Game,entertainment,NaN,12.51,Georgia-Pacific,24-pack
16,GAME-MONO,Board Game - Monopoly,ENTERTAINMENT,NaN,NaN,Campbell's,1pk
17,CARDS-01,Playing Cards,ENTERTAINMENT,Playing,2.45,J.M. Smucker,4pk
18,PLAYCARD-STD,PLAYING CARDS,entertainment,Playing,2.39,Georgia-Pacific,24-pack
19,STREAM-01,Roku Streaming Stick,Electronics,Streaming,16.70,3M Company,12 pack
20,ROKU-STD,Streaming Device,electronics,Streaming,16.99,Anheuser-Busch,12 pack
21,SOUP-CAN,Soup - Canned,Groceries,Canned,1.23,J.M. Smucker,single
22,CNSOUP-01,Canned Soup,GROCERY,NaN,1.19,Generic Supplier,single
23,BREAD-WH,WHITE BREAD,Grocery,Bread,1.53,Procter & Gamble,24-pack
24,WHITEBREAD,WHITE BREAD,grocery,Bread,1.12,Sara Lee,24 pack
25,PB-16,PEANUT BUTTER,GROCERY,Peanut,1.36,Hasbro,bundle
26,PNUTBTR-16,Peanut Butter,GROCERY,Peanut,1.94,Sara Lee,1-pack
27,CNDL-EM,Candles (Emergency),EMERGENCY,Candles,3.81,Frito-Lay,1 pack
28,CANDLE-EMRG,Emergency Candles,EMERGENCY,Candles,3.43,Roku Inc,24pk
29,FAID-01,First-Aid Kit,health,First,6.90,Anheuser-Busch,4 pack
30,FIRSTAID-KIT,First Aid Kit,health,NaN,7.85,J.M. Smucker,4 pack
31,CHRG-PORT,PORTABLE CHARGER,ELECTRONICS,NaN,11.99,Georgia-Pacific,single
32,PORTCHARGER,Portable Phone Charger,ELECTRONICS,Portable,15.03,Johnson & Johnson,12 pack
33,CHIPS-VP,Variety Pack - Chips,snacks,Chips,4.03,Frito-Lay,single
34,CHIPVARIETY,Chips Variety Pack,Snacks,Chips,4.11,Generic Supplier,4-pack
35,PTOWEL-6,Paper Towels,household,Paper,3.85,Campbell's,4 pack
36,PAPERTOWEL6,Paper Towels,HOUSEHOLD,Paper,5.09,Georgia-Pacific,12-pack
37,TP-12,TOILET PAPER 12PK,household,Toilet,5.58,Campbell's,1 pack
38,TOILETPAPER12,Toilet Paper 12-Roll,Household,Toilet,5.75,J.M. Smucker,24-pack
39,DIAP-S3,Baby Diapers - Size 3,baby,Diapers,14.40,Procter & Gamble,single
40,DIAPERS-3,DIAPERS SZ 3,Baby Products,Diapers,13.59,Generic Supplier,6 pack
41,BFORM-01,Infant Formula,Baby,Baby,18.87,Procter & Gamble,4-pack
42,BABYFORMULA,Baby Formula,Baby,NaN,18.25,Sara Lee,6 pack
43,TARP-HD,Heavy Duty Tarp,Emergency,NaN,11.90,J.M. Smucker,12 pack
44,HDTARP-01,TARP - HEAVY DUTY,emergency,Tarp,NaN,J.M. Smucker,24pk

In [13]:
def create_mappings(from_list: list[str], to: str) -> dict[str, str]:
    d = {}
    for fr in from_list:
        d[fr] = to
    return d

CANON = {}
# |= merges dictionaries
CANON |= create_mappings(["SKU#459812", "POPTART-STRAW", "PT_STRAWBERRY"],
                         "PT-12")
CANON |= create_mappings(["WTR-24", "WATER24PK", "WTR_24PK"],
                         "WTR-24")
CANON |= create_mappings(['BG-MONO', 'MONOPOLY-01', 'GAME-MONO'],
                         'BG-MONO')
CANON

{'SKU#459812': 'PT-12',
 'POPTART-STRAW': 'PT-12',
 'PT_STRAWBERRY': 'PT-12',
 'WTR-24': 'WTR-24',
 'WATER24PK': 'WTR-24',
 'WTR_24PK': 'WTR-24',
 'BG-MONO': 'BG-MONO',
 'MONOPOLY-01': 'BG-MONO',
 'GAME-MONO': 'BG-MONO'}

In [14]:
def consolidate(frame: DataFrame):
    out = frame.copy()
    out['canonical_sku'] = out.apply(apply_canonical_sku, axis=1)
    return out

def apply_canonical_sku(row):
    if row['sku'] in CANON:
        return CANON[row['sku']]
    return row['sku']

consolidated = consolidate(df)
consolidated

,sku,product_name,category,subcategory,unit_cost,supplier,package_size,canonical_sku
0,PT-12,pop-tarts strawberry,Breakfast Foods,NaN,1.93,Johnson & Johnson,4-pack,PT-12
1,SKU#459812,Strawberry Pop-Tart,Breakfast,Pop-Tarts,2.26,Roku Inc,4pk,PT-12
2,POPTART-STRAW,Pop-Tarts Strawberry,Breakfast,NaN,2.11,Sara Lee,6 pack,PT-12
3,PT_STRAWBERRY,pop-tarts strawberry,breakfast,Pop-Tarts,NaN,Campbell's,4 pack,PT-12
4,WTR-24,BOTTLED WATER 24PK,Emergency Supplies,Bottled,2.64,Sara Lee,1 pack,WTR-24
5,WATER24PK,Bottled Water 24-Pack,Emergency,Bottled,2.38,Sara Lee,24 pack,WTR-24
6,WTR_24PK,Water - 24 Pack,Emergency,NaN,2.08,Frito-Lay,1 pack,WTR-24
7,BATT-100,BATTERIES AA 4PK,Emergency Supplies,AA,NaN,3M Company,6 pack,BATT-100
8,BAT-AA4,AA Batteries 4-Pack,Emergency Supplies,AA,4.16,Kimberly-Clark,4pk,BAT-AA4
9,BATT_AA_4PK,AA Batteries 4-Pack,Emergency,AA,3.71,Anheuser-Busch,24 pack,BATT_AA_4PK
10,FLASH-01,FLASHLIGHT LED,Emergency,Flashlight,NaN,Frito-Lay,6-pack,FLASH-01
11,LED-FLASH,FLASHLIGHT LED,EMERGENCY,NaN,8.20,Frito-Lay,single,LED-FLASH
12,BEER-24,Light Beer (24-pack),Alcoholic Beverages,NaN,9.62,Hasbro,bundle,BEER-24
13,LTBEER24,Light Beer (24-pack),ALCOHOL,Light,7.61,Kellogg's,bundle,LTBEER24
14,BG-MONO,Monopoly Board Game,ENTERTAINMENT,NaN,9.96,Kimberly-Clark,1pk,BG-MONO
15,MONOPOLY-01,Monopoly Board Game,entertainment,NaN,12.51,Georgia-Pacific,24-pack,BG-MONO
16,GAME-MONO,Board Game - Monopoly,ENTERTAINMENT,NaN,NaN,Campbell's,1pk,BG-MONO
17,CARDS-01,Playing Cards,ENTERTAINMENT,Playing,2.45,J.M. Smucker,4pk,CARDS-01
18,PLAYCARD-STD,PLAYING CARDS,entertainment,Playing,2.39,Georgia-Pacific,24-pack,PLAYCARD-STD
19,STREAM-01,Roku Streaming Stick,Electronics,Streaming,16.70,3M Company,12 pack,STREAM-01
20,ROKU-STD,Streaming Device,electronics,Streaming,16.99,Anheuser-Busch,12 pack,ROKU-STD
21,SOUP-CAN,Soup - Canned,Groceries,Canned,1.23,J.M. Smucker,single,SOUP-CAN
22,CNSOUP-01,Canned Soup,GROCERY,NaN,1.19,Generic Supplier,single,CNSOUP-01
23,BREAD-WH,WHITE BREAD,Grocery,Bread,1.53,Procter & Gamble,24-pack,BREAD-WH
24,WHITEBREAD,WHITE BREAD,grocery,Bread,1.12,Sara Lee,24 pack,WHITEBREAD
25,PB-16,PEANUT BUTTER,GROCERY,Peanut,1.36,Hasbro,bundle,PB-16
26,PNUTBTR-16,Peanut Butter,GROCERY,Peanut,1.94,Sara Lee,1-pack,PNUTBTR-16
27,CNDL-EM,Candles (Emergency),EMERGENCY,Candles,3.81,Frito-Lay,1 pack,CNDL-EM
28,CANDLE-EMRG,Emergency Candles,EMERGENCY,Candles,3.43,Roku Inc,24pk,CANDLE-EMRG
29,FAID-01,First-Aid Kit,health,First,6.90,Anheuser-Busch,4 pack,FAID-01
30,FIRSTAID-KIT,First Aid Kit,health,NaN,7.85,J.M. Smucker,4 pack,FIRSTAID-KIT
31,CHRG-PORT,PORTABLE CHARGER,ELECTRONICS,NaN,11.99,Georgia-Pacific,single,CHRG-PORT
32,PORTCHARGER,Portable Phone Charger,ELECTRONICS,Portable,15.03,Johnson & Johnson,12 pack,PORTCHARGER
33,CHIPS-VP,Variety Pack - Chips,snacks,Chips,4.03,Frito-Lay,single,CHIPS-VP
34,CHIPVARIETY,Chips Variety Pack,Snacks,Chips,4.11,Generic Supplier,4-pack,CHIPVARIETY
35,PTOWEL-6,Paper Towels,household,Paper,3.85,Campbell's,4 pack,PTOWEL-6
36,PAPERTOWEL6,Paper Towels,HOUSEHOLD,Paper,5.09,Georgia-Pacific,12-pack,PAPERTOWEL6
37,TP-12,TOILET PAPER 12PK,household,Toilet,5.58,Campbell's,1 pack,TP-12
38,TOILETPAPER12,Toilet Paper 12-Roll,Household,Toilet,5.75,J.M. Smucker,24-pack,TOILETPAPER12
39,DIAP-S3,Baby Diapers - Size 3,baby,Diapers,14.40,Procter & Gamble,single,DIAP-S3
40,DIAPERS-3,DIAPERS SZ 3,Baby Products,Diapers,13.59,Generic Supplier,6 pack,DIAPERS-3
41,BFORM-01,Infant Formula,Baby,Baby,18.87,Procter & Gamble,4-pack,BFORM-01
42,BABYFORMULA,Baby Formula,Baby,NaN,18.25,Sara Lee,6 pack,BABYFORMULA
43,TARP-HD,Heavy Duty Tarp,Emergency,NaN,11.90,J.M. Smucker,12 pack,TARP-HD
44,HDTARP-01,TARP - HEAVY DUTY,emergency,Tarp,NaN,J.M. Smucker,24pk,HDTARP-01